config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get 'sign_up', to: 'users/registrations#new'
  end
  
  root to: 'time_sheets#show'

  resources :users, only: [] do
    resources :time_sheets, only: [:show] do
      member do
        post :toggle_timer
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/time_sheet.rb
class TimeSheet < ApplicationRecord
  validates :name, presence: true

  has_many :time_sheet_entries, dependent: :destroy
  belongs_to :user

  def start_new_entry
    set_pst_timezone
    TimeSheetEntry.create(time_sheet: self, from: Time.zone.now, to: "")
  end

  def stop_entry
    set_pst_timezone
    time_sheet_entry = time_sheet_entries.last
    time_sheet_entry.to = Time.zone.now
    time_sheet_entry.duration = Time.at(time_sheet_entry.to - time_sheet_entry.from)
    time_sheet_entry.save
  end

  private

  def set_pst_timezone
    Time.zone = 'Pacific Time (US & Canada)'
  end
end

app/models/time_sheet_entry.rb
class TimeSheetEntry < ApplicationRecord
  validates_datetime :from, presence: true
  validates_datetime :to, allow_blank: true, after: :from

  belongs_to :time_sheet

  default_scope { order(from: :asc) }

  def start_time
    from.strftime('%A, %d %b %Y %l:%M:%S %p')
  end

  def end_time
    to.strftime('%A, %d %b %Y %l:%M:%S %p')
  end

  def time_duration
    duration.utc.strftime("%H:%M:%S")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }

  has_one :time_sheet, dependent: :destroy

  after_create :create_time_sheet


  private

  def create_time_sheet
    TimeSheet.create(name: "Project Time Sheet", user: self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/time_sheets_controller.rb
class TimeSheetsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_user
  before_action :get_time_sheet

  def show
  end

  def toggle_timer
    if timer_started?
      @time_sheet.start_new_entry
      render json: {}, status: :ok
    else
      @time_sheet.stop_entry
      @time_sheet_entry = @time_sheet.time_sheet_entries.last
      render 'toggle_timer.js'
    end
  end

  private

  def get_time_sheet
    @time_sheet = @user.time_sheet
  end

  def get_user
    @user = current_user
  end

  def timer_started?
    if params[:time_sheet][:timer_state] == "1"
      return true
    else
      return false
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute, :name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimeTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <% if user_signed_in? %>
        <%= link_to('Logout', destroy_user_session_path, method: :delete) %> 
      <% end %>
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/time_sheets/_stop_entry.html.erb
<tr>
  <td class="time-sheet-entry"><%= @time_sheet_entry.start_time %></td>
  <td class="time-sheet-entry"><%= @time_sheet_entry.end_time %></td>
  <td class="time-sheet-entry"><%= @time_sheet_entry.time_duration %></td>
</tr>

app/views/time_sheets/_toggle_timer.html.erb
<tr>
  <td class="time-sheet-entry"><%= @time_sheet_entry.start_time %></td>
  <td class="time-sheet-entry"><%= @time_sheet_entry.end_time %></td>
  <td class="time-sheet-entry"><%= @time_sheet_entry.time_duration %></td>
</tr>

app/views/time_sheets/show.html.erb
<h1>Time Sheet Tracker</h1>
<br>


<%= form_for @time_sheet, url: toggle_timer_user_time_sheet_url(@user, @time_sheet), method: :post, remote: true do |f| %>
  <%= f.hidden_field :timer_state, value: 0 %>
  <%= f.submit "Start", class: "btn btn-primary btn-lg", id: "time-button" %>
<% end %>

<br>
<br>
<h2>Timer</h2>
<h2 id="basicUsage">00:00:00</h2>
<br>
<br>
<h3>Time Sheet</h3>
<table id=time-sheet class="table table-sm col-6">
  <tr class="thead-dark">
    <th scope="col">Start Time</th>
    <th scope="col">End Time</th>
    <th scope="col">Duration</th>
  </tr>

  <% @time_sheet.time_sheet_entries.each do |time_sheet_entry| %>
    <% if time_sheet_entry.to.present? %>
      <tr scope="row">
        <td style="width: 40%"><%= time_sheet_entry.start_time %></td>
        <td style="width: 40%"><%= time_sheet_entry.end_time %></td>
        <td style="width: 20%"><%= time_sheet_entry.time_duration %></td>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/time_sheets/toggle_timer.js.erb
$("#time-sheet").append("<%= j render partial: 'toggle_timer', locals: { time_sheet_entry: @time_sheet_entry } %>");

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>